# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c262184055120cc37a1d717602e909ca3b66c4ae849bcf855c5b513124936006d8253e6658bd2fa68ac88a9a5bcbc9df01c80771b3a56eae01d22d06b8772333

test:
  secret_key_base: b911735d4995ffdc6a751f367a1d9d26e7e0c10e8369507198e0e81fbc1521b7072278c38f3e4fc1a97577971ff9bfb949c1ab505306fa13d7de4452685ec7c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
